# Generated by Django 4.1.3 on 2022-11-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phrase',
            name='phrase',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
