# Generated by Django 4.1.3 on 2022-11-19 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0005_suggestions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestions',
            name='phrase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suggestion_phrase', to='translator.phrase'),
        ),
    ]
